### ISSUE TITLE
Feature Request Aria Plogue Support

### ISSUE THREAD

**Issue by tank-trax** [git-moss/ConvertWithMoss#43]
Not sure if this is doable

sforzando SFZ Player Plugin samples support. they use non-standard op codes which makes these SFZ's unreadable in most samplers

https://sfzinstruments.github.io/

Thanks

**Comment by git-moss** [comment]
Not sure what's your question. Are you asking to support non-standard opcodes or do you want to remove them?

**Comment by tank-trax** [comment]
Whichever works. So far the only SFZ player I found that loads these is Plogue Sfzorando. I am on Linux and rarely if ever use WINE. Prefer a Linux solution.

**Comment by audio2000** [comment]
@tank-trax
I apologize if what I am saying does not make sense based on what you are looking for.
I am using Linux as well and do not prefer to have to use WINE either so we are in the same boat :)
I am looking for something similar as well, but sure if exactly the same.
I am not sure how to word this either because I do not know if it is these non-standard Aria based opcodes causing them not to work
OR 
if it is how Sforzando based instruments are setup in general, because they appear to use a different folder structure and different use of .sfz files (seems to use many of them linked together) that is making them not work in Linux/non Sforzando based player plugins.

I guess a big question is, if anyone else knows the answer to this.
Do ALL Sforzando based SFZ instruments use these non-standard optcodes?  Meaning do ALL Sforzando based instruments require these non-standard opcodes to actually make these SFZ instruments work in Sforzando?  I am not sure if the folder structure info I mentioned above has something to do with these opcodes.

Again not sure if my request is the same as yours, so I am going to stop here.  I do not want to take over your post.  I was working on a separate post based on the folder structure of these instruments used by Sforzando, I will make that post and link yours if you or anyone else is interested.

I apologize if this is not the same issue.
Thank You

**Comment by git-moss** [comment]
> Not sure if this is doable
> 
> sforzando SFZ Player Plugin samples support. they use non-standard op codes which makes these SFZ's unreadable in most samplers
> 
> https://sfzinstruments.github.io/
> 
> Thanks

If the unknown opcodes are the only reason that these files cannot be read you can simply convert from SFZ to SFZ with ConvertWithMoss which will remove them.
